name: airline_sentiment
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - nltk
  - scikit-learn
  - jupyterlab
  - pip
  - pip:
    - tensorflow
    - keras
